### ISSUE TITLE
Notebook dependency (ndh_analysis_functions.py) not found

### ISSUE THREAD

**Issue by bwalsh** [uc-cdis/ndh-demo#5]
https://github.com/uc-cdis/ndh-demo/blame/master/demo/DAIDS_notebook/CHARLIE_demo.ipynb#L23

points to `https://github.com/uc-cdis/ndh-demo/blob/master/demo/ndh_analysis_functions.py`

**Comment by bwalsh** [comment]
User error.  The file `ndh_analysis_functions.py` is in the current directory.  However, comment in notebook is misleading.

**Comment by zflamig** [comment]
Corrected, thanks!
